Nome1= input("dimmi il tuo nome")
Nome2= input("dimmi il tuo nome")
Nome3= input("dimmi il tuo nome")
Cognome1=input("dimmi il tuo cognome")
Cognome2=input("dimmi il tuo cognome")
Cognome3=input("dimmi il tuo cognome")
Età1=int(input("dimmi il tuo età"))
Età2=int(input("dimmi la tua età"))
Età3=int(input("dimmi la tua Età"))
Nome1Voto1=int(input("dammi un voto"))
Nome1Voto2=int(input("dammi un voto"))
Nome1Voto3=int(input("dammi un voto"))
Nome1Voto4=int(input("dammi un voto"))
Nome1Voto5=int(input("dammi un voto"))
Nome2Voto1=int(input("dammi un voto"))
Nome2Voto2=int(input("dammi un voto"))
Nome2Voto3=int(input("dammi un voto"))
Nome2Voto4=int(input("dammi un voto"))
Nome2Voto5=int(input("dammi un voto"))
Nome3Voto1=int(input("dammi un voto"))
Nome3Voto2=int(input("dammi un voto"))
Nome3Voto3=int(input("dammi un voto"))
Nome3Voto4=int(input("dammi un voto"))
Nome3Voto5=int(input("dammi un voto"))
Somma1= Nome1Voto1+Nome1Voto2+Nome1Voto3+Nome1Voto4+Nome1Voto5
Somma2= Nome2Voto1+Nome2Voto2+Nome2Voto3+Nome2Voto4+Nome2Voto5
Somma3= Nome3Voto1+Nome3Voto2+Nome3Voto3+Nome3Voto4+Nome3Voto5
Media1= Somma1/5
Media2= Somma2/5
Media3= Somma3/5
print(Nome1,Cognome1,"ha", Età1, "ha una media di", Media1, Nome2, Cognome2,"ha",Età2, "ha una media di", Media2,Nome3,Cognome3,"ha",Età3, "ha una media di" ,Media3,", il ragazzo con la media più alta è",Nome1,Cognome1)
